AllCops:
  Exclude:
    - 'gemfiles/**'
  TargetRubyVersion: 2.4

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

# Enforcing this results in a lot of unnecessary indentation.
Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/haml_lint/spec/**/*.rb'

Layout/DotPosition:
  EnforcedStyle: leading

Style/FormatString:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'bin/haml-lint'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*'
    - 'lib/haml_lint/spec/**/*.rb'

Lint/NestedPercentLiteral:
  Exclude:
    - lib/haml_lint/linter/multiline_script.rb

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 24

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/haml_lint/spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/haml_lint/spec/**/*.rb'

# Prefer curly braces except for %i/%w/%W, since those return arrays.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

# Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
# a "has-a" relationship.
Naming/PredicateName:
  Enabled: false

Style/SignalException:
  Enabled: false

# Forcing a particular name (e.g. |a, e|) for inject methods prevents you from
# choosing intention-revealing names.
Style/SingleLineBlockParams:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Lint/Void:
  Enabled: false
