language: ruby

sudo: false

cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3.6
  - 2.4.3
  - 2.5.0

gemfile:
  - gemfiles/haml4.gemfile
  - gemfiles/haml5.gemfile

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

before_install:
  - gem update --system
  - gem update --remote bundler

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
